//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BokhandelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LagerSaldo
    {
        public int ButikID { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> Antal { get; set; }
    
        public virtual Butiker Butiker { get; set; }
        public virtual Böcker Böcker { get; set; }
    }
}
